const LEAGUES={EPL:{name:'Premier League',code:'eng.1',country:'England'},LaLiga:{name:'LaLiga',code:'esp.1',country:'Spain'},Bundesliga:{name:'Bundesliga',code:'ger.1',country:'Germany'},SerieA:{name:'Serie A',code:'ita.1',country:'Italy'},Ligue1:{name:'Ligue 1',code:'fra.1',country:'France'}};
let active='EPL', leagueData={}, allMatches=[];
const $=s=>document.querySelector(s);
function tabs(){ $('#leagueTabs').innerHTML=Object.entries(LEAGUES).map(([k,v])=>`<button class="${k===active?'active':''}" data-league="${k}">${v.name}</button>`).join('');document.querySelectorAll('[data-league]').forEach(b=>b.onclick=()=>{active=b.dataset.league;tabs();render()}) }
function esc(x){return String(x??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]))}
function crest(team){return team?.logo?`<img class="crest" src="${esc(team.logo)}" onerror="this.style.display='none'">`:''}
function statusText(g){if(g.status?.type?.state==='in')return `<span class="status live">● LIVE ${esc(g.status.displayClock||'')}</span>`;if(g.status?.type?.completed)return `<span class="status">FT</span>`;return `<span class="status">${esc(g.status?.type?.shortDetail||'Scheduled')}</span>`}
async function fetchLeague(key){const code=LEAGUES[key].code;const [score,stand]=await Promise.all([fetch(`https://site.api.espn.com/apis/site/v2/sports/soccer/${code}/scoreboard?limit=50`).then(r=>r.json()),fetch(`https://site.api.espn.com/apis/site/v2/sports/soccer/${code}/standings`).then(r=>r.json()).catch(()=>({}))]);return {events:score.events||[],standings:stand?.children?.[0]?.standings?.entries||[]}}
async function load(){try{const keys=Object.keys(LEAGUES);const data=await Promise.all(keys.map(fetchLeague));leagueData=Object.fromEntries(keys.map((k,i)=>[k,data[i]]));allMatches=keys.flatMap(k=>data[keys.indexOf(k)].events.map(e=>({...e,league:k})));render();$('#lastUpdated').textContent=new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit',second:'2-digit'});}catch(e){$('#matches').innerHTML='<div class="empty">Could not load live data right now. Try refresh in a moment.</div>';console.error(e)}}
function render(){const d=leagueData[active]||{events:[],standings:[]};$('#matchTitle').textContent=`${LEAGUES[active].name} · Matches`;$('#tableTitle').textContent=`${LEAGUES[active].name} · Standings`;const ev=d.events;$('#matchCount').textContent=`${ev.length} match${ev.length===1?'':'es'}`;$('#matches').innerHTML=ev.length?ev.map(g=>{const c=g.competitions?.[0],teams=c?.competitors||[];const home=teams.find(t=>t.homeAway==='home')||teams[0]||{},away=teams.find(t=>t.homeAway==='away')||teams[1]||{};const dt=new Date(g.date);return `<article class="match"><div class="time">${dt.toLocaleDateString([], {weekday:'short',day:'numeric',month:'short'})}<br>${dt.toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}${statusText(g)}</div><div class="teams"><div class="team"><span class="team-name">${crest(home.team)}${esc(home.team?.displayName)}</span><span class="score">${home.score??'–'}</span></div><div class="team"><span class="team-name">${crest(away.team)}${esc(away.team?.displayName)}</span><span class="score">${away.score??'–'}</span></div></div><div class="match-meta">${esc(g.season?.slug||'2026/27')}</div></article>`}).join(''):'<div class="empty">No matches listed for this league today.</div>';
const entries=d.standings||[];$('#standings').innerHTML=entries.length?entries.map((x,i)=>{const s=x.stats||[];const val=n=>s.find(a=>a.name===n)?.value??0;const team=x.team||{};return `<tr><td>${i+1}</td><td><span class="club">${crest(team)}${esc(team.displayName)}</span></td><td>${val('gamesPlayed')}</td><td>${val('wins')}</td><td>${val('ties')}</td><td>${val('losses')}</td><td>${val('pointDifferential')}</td><td class="pts">${val('points')}</td></tr>`}).join(''):'<tr><td colspan="8" style="text-align:center;color:#718198;padding:25px">Standings unavailable</td></tr>'}
function reply(q){const l=leagueData[active],events=l?.events||[],stand=l?.standings||[];const s=q.toLowerCase();let text;if(s.includes('live')){const live=events.filter(e=>e.status?.type?.state==='in');text=live.length?`There ${live.length===1?'is':'are'} ${live.length} live match${live.length===1?'':'es'} in the ${LEAGUES[active].name}: ${live.map(e=>e.name).join(', ')}.`:`No ${LEAGUES[active].name} matches are live right now.`}else if(s.includes('top')||s.includes('table')||s.includes('first')){text=stand[0]?.team?.displayName?`${stand[0].team.displayName} are currently top of the ${LEAGUES[active].name} table on ${stand[0].stats?.find(x=>x.name==='points')?.value??0} points.`:'I can’t see the table data right now.'}else if(s.includes('today')||s.includes('match')||s.includes('game')){text=events.length?`There are ${events.length} listed matches in the ${LEAGUES[active].name}.`:`There are no listed matches for this league today.`}else{text=`I can help with live matches, today's games, and the ${LEAGUES[active].name} table. Try “What's live?” or “Who is top of the table?”`};return text}
function addMsg(t,who){const el=document.createElement('div');el.className='msg '+who;el.textContent=t;$('#chat').appendChild(el);$('#chat').scrollTop=99999}
$('#chatForm').onsubmit=e=>{e.preventDefault();const i=$('#chatInput'),q=i.value.trim();if(!q)return;addMsg(q,'user');i.value='';setTimeout(()=>addMsg(reply(q),'bot'),250)};document.querySelectorAll('[data-q]').forEach(b=>b.onclick=()=>{addMsg(b.dataset.q,'user');setTimeout(()=>addMsg(reply(b.dataset.q),'bot'),250)});$('#refreshBtn').onclick=load;tabs();load();setInterval(load,30000);
